export {default as Header} from './Header'
export {default as Hero } from './Hero'
export {default as Button} from './Button'
export {default as About} from './About'
export {default as Services} from './Services'
export {default as Form} from './Form'
export {default as Footer } from './Footer'
export {default as AboutHero} from './AboutHero'
export {default as AboutStatement} from './AboutStatement'
export {default as NameCard} from './smallComponents/NameCard'
export {default as Grid} from './Grid'